all: compile link

compile:
	g++ -DSFML_STATIC -ISFML/include -c function.cpp -o SFML/function.o
	g++ -DSFML_STATIC -ISFML/include -c main.cpp -o SFML/main.o 

link:
	g++ -o main SFML/function.o SFML/main.o -static -LSFML/lib \
		-lsfml-graphics-s -lsfml-window-s -lsfml-system-s \
		-lwinmm -lopengl32 -lgdi32 -lfreetype \
		-std=c++17

# mingw32-make -f MakeFile